spring.datasource.url=jdbc:postgresql://ep-delicate-cherry-a4c46ffq-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VTC2dgIw3fkt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# MVC/FreeMarker Settings
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh

spring.datasource.url=jdbc:postgresql://ep-delicate-cherry-a4c46ffq-pooler.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_VTC2dgIw3fkt&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.cache=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jackson.deserialization.fail-on-unknown-properties=false     