spring.datasource.url=jdbc:postgresql://ep-delicate-cherry-a4c46ffq-pooler.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_VTC2dgIw3fkt&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.cache=false