spring.application.name=hobby-circles
spring.datasource.url=jdbc:postgresql://ep-delicate-cherry-a4c46ffq-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VTC2dgIw3fkt
spring.jpa.hibernate.ddl-auto=update

# This helps you see what's happening in the console
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE